"""initial schema

Revision ID: 4dc010d98fab
Revises: 
Create Date: 2026-06-07 19:29:13.029860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc010d98fab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_tracks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('spotify_user_id', sa.String(length=64), nullable=False),
    sa.Column('track_id', sa.String(length=64), nullable=False),
    sa.Column('track_name', sa.String(length=256), nullable=False),
    sa.Column('artists', sa.Text(), nullable=False),
    sa.Column('album', sa.String(length=256), nullable=False),
    sa.Column('album_id', sa.String(length=64), nullable=False),
    sa.Column('album_image_url', sa.String(length=512), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('explicit', sa.Boolean(), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=False),
    sa.Column('track_url', sa.String(length=512), nullable=False),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('audio_features', sa.JSON(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cached_tracks_spotify_user_id'), 'cached_tracks', ['spotify_user_id'], unique=False)
    op.create_table('playlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('spotify_user_id', sa.String(length=64), nullable=False),
    sa.Column('spotify_playlist_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filter_criteria', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlists_spotify_user_id'), 'playlists', ['spotify_user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('spotify_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_playlists_spotify_user_id'), table_name='playlists')
    op.drop_table('playlists')
    op.drop_index(op.f('ix_cached_tracks_spotify_user_id'), table_name='cached_tracks')
    op.drop_table('cached_tracks')
    # ### end Alembic commands ###
